name: Linux. Use Conan to install, configure and build.
on:
  pull_request:
  workflow_dispatch:
  push:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: vvvar/juce-conan
          path: juce-conan
      - run: |
          sudo apt update -y
          sudo apt install -y libasound2-dev libjack-jackd2-dev \
              ladspa-sdk \
              libcurl4-openssl-dev  \
              libfreetype6-dev \
              libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev \
              libwebkit2gtk-4.0-dev \
              libglu1-mesa-dev mesa-common-dev
      - run: pip3 install conan --upgrade
      - run: conan create --profile:all conan/linux juce-conan
      - run: conan install --profile:all conan/linux --build=missing .
      - run: conan build --profile:all conan/linux .
      - run: ./build/Release/main
