name: Windows. Use Conan to install, configure and build.

on:
  pull_request:
  workflow_dispatch:
  push:
jobs:
  run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: vvvar/juce-conan
          path: juce-conan
      - run: pip3 install conan --upgrade
      - run: conan profile detect
      - run: |
          $profilePath = "C:\Users\runneradmin\.conan2\profiles\default"
          (Get-Content $profilePath).replace('compiler.cppstd=14', 'compiler.cppstd=20') | Set-Content $profilePath
        shell: pwsh
      - run: conan create juce-conan
      - run: conan install --build=missing .
      - run: conan build .
      - run: .\build\Release\main
        shell: pwsh
